# Generated by Django 5.1.3 on 2024-11-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.FileField(max_length=255, null=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.FileField(max_length=255, null=True, upload_to='icons/', verbose_name='Icon'),
        ),
    ]
