# Generated by Django 5.1.3 on 2024-11-07 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=50, null=True)),
                ('sequence_number', models.IntegerField(default=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_city_list', to='app.city')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_state_list', to='app.state')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
            },
        ),
        migrations.CreateModel(
            name='ZoneBoundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=20, null=True)),
                ('longitude', models.CharField(max_length=20, null=True)),
                ('sequence_number', models.IntegerField(default=1, null=True)),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='app.zone')),
            ],
            options={
                'verbose_name': 'Zone Boundry',
                'verbose_name_plural': 'Zone Boundries',
                'unique_together': {('zone', 'latitude', 'longitude')},
            },
        ),
    ]
