# Generated by Django 5.1.3 on 2024-11-07 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_zone_zoneboundry'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together={('state', 'city', 'zone_name')},
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50, null=True)),
                ('sequence_number', models.IntegerField(default=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_city_list', to='app.city')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_state_list', to='app.state')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_zone_list', to='app.zone')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'unique_together': {('state', 'city', 'zone', 'location_name')},
            },
        ),
    ]
