# Generated by Django 5.1.3 on 2024-11-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_zone_unique_together_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('state', 'city_name')},
        ),
    ]
