# Generated by Django 5.1.3 on 2024-11-07 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_state_state_name_alter_city_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationBoundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=20, null=True)),
                ('longitude', models.CharField(max_length=20, null=True)),
                ('sequence_number', models.IntegerField(default=1, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='app.location')),
            ],
            options={
                'verbose_name': 'Location Boundry',
                'verbose_name_plural': 'Location Boundries',
                'unique_together': {('location', 'latitude', 'longitude')},
            },
        ),
    ]
