# Generated by Django 5.1.3 on 2024-11-08 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profile List'},
        ),
    ]
