# Generated by Django 5.1.3 on 2024-11-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_userprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='zone_color_code',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
