# Generated by Django 5.1.3 on 2024-11-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_zone_zone_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='zone_color_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
