# Generated by Django 5.1.3 on 2024-11-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_zone_zone_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='boundry_file',
            field=models.FileField(max_length=255, null=True, upload_to='city_boundry/', verbose_name='City Boundry'),
        ),
    ]
