# Generated by Django 5.1.3 on 2024-11-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_city_boundry_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='boundry_color_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='map_fill_color_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
