# Generated by Django 5.1.3 on 2024-11-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_city_center_latitude_city_center_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='map_max_zoom',
            field=models.IntegerField(default=20, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='map_min_zoom',
            field=models.IntegerField(default=11, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='map_zoom',
            field=models.IntegerField(default=11, null=True),
        ),
    ]
