# Generated by Django 5.1.3 on 2024-11-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_city_map_max_zoom_city_map_min_zoom_city_map_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='name_color_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
