# Generated by Django 5.1.3 on 2024-11-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_zone_name_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='name_color_code',
            field=models.CharField(blank=True, default='#000000', max_length=7, null=True),
        ),
    ]
