# Generated by Django 5.1.3 on 2024-11-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_zone_name_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='area',
            field=models.CharField(blank=True, default='NULL', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='population',
            field=models.CharField(blank=True, default='NULL', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='traffic',
            field=models.CharField(blank=True, default='NORMAL', max_length=20, null=True),
        ),
    ]
