# Generated by Django 5.1.3 on 2024-11-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_mobileotp_tempuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='boundry_color_code',
            field=models.CharField(default='#000000', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='fill_color_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='name_color_code',
            field=models.CharField(blank=True, default='#000000', max_length=7, null=True),
        ),
    ]
