# Generated by Django 5.1.3 on 2024-12-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_location_boundry_color_code_location_fill_color_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='boundry_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='boundry_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='boundry_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
