# Generated by Django 5.1.3 on 2024-12-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_city_boundry_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zoneboundry',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='zoneboundry',
            name='zone',
        ),
        migrations.DeleteModel(
            name='LocationBoundry',
        ),
        migrations.DeleteModel(
            name='ZoneBoundry',
        ),
    ]
