# Generated by Django 5.1.3 on 2024-11-15 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0009_zone_zone_color_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drone_video_city', to='app.city')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drone_video_state', to='app.state')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drone_video_zone', to='app.zone')),
            ],
            options={
                'verbose_name': 'Drone Video',
                'verbose_name_plural': 'Drone Video List',
                'unique_together': {('state', 'city', 'zone', 'video_url')},
            },
        ),
    ]
