# Generated by Django 5.1.3 on 2024-11-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dronevideo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dronevideo',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
