# Generated by Django 5.1.3 on 2024-11-15 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dronevideo', '0002_alter_dronevideo_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneVideoPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=20, null=True)),
                ('longitude', models.CharField(max_length=20, null=True)),
                ('sequence_number', models.IntegerField(default=1, null=True)),
                ('drone_video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drone_video_path', to='dronevideo.dronevideo')),
            ],
            options={
                'verbose_name': 'Drone Video Path',
                'verbose_name_plural': 'Drone Video Path',
                'unique_together': {('drone_video', 'latitude', 'longitude')},
            },
        ),
    ]
