# Generated by Django 5.1.3 on 2024-11-16 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dronevideo', '0003_dronevideopath'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dronevideopath',
            options={'verbose_name': 'Drone Video Path', 'verbose_name_plural': 'Drone Video Path List'},
        ),
    ]
