# Generated by Django 5.1.3 on 2024-11-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dronevideo', '0004_alter_dronevideopath_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dronevideo',
            name='path_color_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
