# Generated by Django 5.1.3 on 2024-11-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dronevideo', '0005_dronevideo_path_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dronevideo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
