# Generated by Django 5.1.3 on 2024-12-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dronevideo', '0007_dronevideo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dronevideo',
            name='path_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
